alias rm='rm -i'
alias cp='cp -i'
alias rv='mv -i'

if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export PS1='\n\e[1;37m[\e[m\e[1;32m\u\e[m\e[1;33m@\e[m\e[1;35m\h\e[m \e[4m`pwd`\e[m\e[1;37m]\e[m\e[1;36m\e[m\n\$'
export EDITOR=vim
alias vi='vim'

